version: 0.1

log:
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: redis
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

http:
  addr: :5000
  http:
    headers:
      # TODO after DNS configuration
      # Access-Control-Allow-Origin: [ 'http://registry.example.com' ]
      Access-Control-Allow-Origin: ['*']
      Access-Control-Allow-Credentials: [ true ]
      Access-Control-Allow-Headers: ['Authorization', 'Accept']
      Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE' ]
      Access-Control-Expose-Headers: ['Docker-Content-Digest']

auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3