version: "3.7"
services:
  registry:
    image: registry:latest
    restart: always
    container_name: registry
    volumes:
      - storage:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
#    networks:
#      - registry-ui-net

#  ui:
#    image: joxit/docker-registry-ui:1.5-static
#    container_name: registry-ui
#    restart: always
#    ports:
#      - "${UI_PORT}:80"
#    environment:
#      # REGISTRY_URL: $REGISTRY_URL
#      REGISTRY_TITLE: $REGISTRY_TITLE
#      CATALOG_ELEMENTS_LIMIT: $CATALOG_ELEMENTS_LIMIT
#      SINGLE_REGISTRY: "true"
#      DELETE_IMAGES: "true"
#      # NGINX_PROXY_PASS_URL: http://registry:5000
#    depends_on:
#      - registry
#    networks:
#      - registry-ui-net
#
#networks:
#  registry-ui-net:

volumes:
    storage:
      driver: local
